### ISSUE TITLE
Missing function at pdf_utils.py (analyze_pages)

### ISSUE THREAD

**Issue by busekuz** [HazyResearch/pdftotree#105]
Hello all!

 

I have been trying to run extract_tables on given paleo dataset.
But I get an import error at TableExtractML.py when I run the command as,

 

> Traceback (most recent call last):
>   File "bin/extract_tables", line 13, in <module>
>     **from pdftotree.ml.TableExtractML import TableExtractorML**
>   File "C:\Users\b\Anaconda3\envs\nlp\lib\site-packages\pdftotree\ml\TableExtractML.py", line 21, in <module>
>     **from pdftotree.utils.pdf.pdf_utils import analyze_pages, normalize_pdf**
> **ImportError: cannot import name 'analyze_pages' from 'pdftotree.utils.pdf.pdf_utils**' (C:\Users\b\Anaconda3\envs\nlp\lib\site-packages\pdftotree\utils\pdf\pdf_utils.py)
> 

 

After that I have checked and seen that there is no analyze_pages function anywhere.
Is it possible that there is a mistake at naming or something else?

 

Thanks!

**Comment by HiromuHota** [comment]
This issue was introduced by #79 and happens on v0.5.0.
